equire('dotenv').config();
const express = require('express');
const userRoutes = require('./routes/user.routes');
const todoRoutes = require('./routes/todo.routes');
const errorHandler = require('./middlewares/error.middleware');
const app = express();
app.use(express.json());
app.use('/api/users', userRoutes);
app.use('/api/todos', todoRoutes);
app.use(errorHandler);
module.exports = app;
